### ISSUE TITLE
请问荣耀9的屏幕dts是在哪个目录中的

### ISSUE THREAD

**Issue by li6848** [maimaiguanfan/android_kernel_huawei_hi3660#6]
请问荣耀9的屏幕dts是在哪个目录中的，想拿荣耀9废物利用，把他的屏幕卸下来放开发板上点亮。请问大佬可以告知屏幕的dts是在仓库的哪个目录中……

**Comment by maimaiguanfan** [comment]
你好，可能是 arch/arm64/boot/dts/ 里面？我不是大佬，这个我也不确定
